function P = load_parfor(M, N, B, mu, tmp)
    
% load(['D:/Joao/data_fn2/M_' num2str(M) '_N_' num2str(N) '_B_' num2str(B)...
%    '_T_' num2str(tmp) '_mu_' num2str(mu) '.mat']...
%     ,'P')

load(['data_fn/M_' num2str(M) '_N_' num2str(N) '_B_' num2str(B)...
    '_T_' num2str(tmp) '_mu_' num2str(mu) '.mat']...
     ,'P')

end