function save_parfor(M, N, A, B, T, mu, P)
    
save(['data_fn/M_' num2str(M) '_N_' num2str(N) '_A_' num2str(A)... 
    '_B_' num2str(B) '_T_' num2str(T) '_mu_' num2str(mu) '.mat']...
            ,'M', 'N', 'A', 'B', 'P', 'T', 'mu')
end