function saveP_fn(M, F, C, A, T, mu, P, dF, dC, dA, dN, g, mm)
% saveP_fn(M, F, C, A, T, mu, P, dF, dC, dA,, dN, g, mm)
% This function allows to save the population and distance matrix in
% generation T for specific parameters.
    
save(['../data_3CDH/M_' num2str(M) '_F_' num2str(F) '_C_' num2str(C)... 
    '_A_' num2str(A) '_T_' num2str(T) '_mu_' num2str(mu) ...
     '_mm_' num2str(mm) '.mat']...
            ,'M', 'F', 'A', 'C', 'P', 'T', 'mu', 'dF', 'dC', 'dA', 'dN',...
            'g','mm')

end